/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loja.br.facens.ads.forms;

import loja.br.facens.ads.conexoes.MySQL;
import loja.br.facens.ads.classes.Produto;
import javax.swing.JOptionPane;


/**
 *
 * @author aluno
 */
public class UICadProdutos extends javax.swing.JFrame {

    /**
     * Creates new form UICadProdutos
     */
    MySQL conectar = new MySQL();
    Produto produto = new Produto();
    
    public UICadProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpIndiceCadastro = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblTamanho = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        lblFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtPrecoCusto = new javax.swing.JTextField();
        lblPrecoCusto = new javax.swing.JLabel();
        lblPrecoVenda = new javax.swing.JLabel();
        txtPrecoVenda = new javax.swing.JTextField();
        txtICMS = new javax.swing.JTextField();
        lblICMS = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblProdutoConsultar = new javax.swing.JLabel();
        txtProdutoConsultar = new javax.swing.JTextField();
        lblDescricaoConsultar = new javax.swing.JLabel();
        txtDescricaoConsultar = new javax.swing.JTextField();
        lblTamanhoConsultar = new javax.swing.JLabel();
        txtTamanhoConsultar = new javax.swing.JTextField();
        lblFornecedorConsultar = new javax.swing.JLabel();
        txtFornecedorConsultar = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtPrecoCustoConsultar = new javax.swing.JTextField();
        lblPrecoCustoConsultar = new javax.swing.JLabel();
        lblPrecoVendaConsultar = new javax.swing.JLabel();
        txtPrecoVendaConsultar = new javax.swing.JTextField();
        txtICMSConsultar = new javax.swing.JTextField();
        lblICMSConsultar = new javax.swing.JLabel();
        btnLimparConsultar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tpIndiceCadastro.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tpIndiceCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tpIndiceCadastro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14))); // NOI18N

        lbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl.setText("Produto:");

        txtProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbl1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl1.setText("Descrição:");

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblTamanho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTamanho.setText("Tamanho:");

        txtTamanho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblFornecedor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFornecedor.setText("Fornecedor:");

        txtFornecedor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Valores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtPrecoCusto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblPrecoCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPrecoCusto.setForeground(new java.awt.Color(255, 0, 0));
        lblPrecoCusto.setText("Preço de custo:");

        lblPrecoVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPrecoVenda.setForeground(new java.awt.Color(0, 153, 0));
        lblPrecoVenda.setText("Preço de venda:");

        txtPrecoVenda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtICMS.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblICMS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblICMS.setText("ICMS:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPrecoCusto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblICMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtICMS, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(txtPrecoVenda)
                    .addComponent(txtPrecoCusto))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/br/facens/ads/img/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/br/facens/ads/img/Salvar.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpIndiceCadastro.addTab("Cadastrar", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consultar Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14))); // NOI18N

        lblProdutoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblProdutoConsultar.setText("Produto:");

        txtProdutoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblDescricaoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDescricaoConsultar.setText("Descrição:");

        txtDescricaoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblTamanhoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTamanhoConsultar.setText("Tamanho:");

        txtTamanhoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblFornecedorConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFornecedorConsultar.setText("Fornecedor:");

        txtFornecedorConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Valores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtPrecoCustoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblPrecoCustoConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPrecoCustoConsultar.setForeground(new java.awt.Color(255, 0, 0));
        lblPrecoCustoConsultar.setText("Preço de custo:");

        lblPrecoVendaConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPrecoVendaConsultar.setForeground(new java.awt.Color(0, 153, 0));
        lblPrecoVendaConsultar.setText("Preço de venda:");

        txtPrecoVendaConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtICMSConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblICMSConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblICMSConsultar.setText("ICMS:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPrecoCustoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecoVendaConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblICMSConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtICMSConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(txtPrecoVendaConsultar)
                    .addComponent(txtPrecoCustoConsultar))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecoCustoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoCustoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecoVendaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoVendaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblICMSConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICMSConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnLimparConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimparConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/br/facens/ads/img/limpar.png"))); // NOI18N
        btnLimparConsultar.setText("Limpar");
        btnLimparConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparConsultarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/br/facens/ads/img/binoculars.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/br/facens/ads/img/updated.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/br/facens/ads/img/delete.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTamanhoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFornecedorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFornecedorConsultar)
                                            .addComponent(txtTamanhoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnAtualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(btnDeletar)
                                        .addGap(27, 27, 27))))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(lblDescricaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(518, 518, 518))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(lblProdutoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtProdutoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnLimparConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(txtDescricaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProdutoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProdutoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultar)
                        .addComponent(btnLimparConsultar)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFornecedorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFornecedorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTamanhoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTamanhoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeletar)
                            .addComponent(btnAtualizar))
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpIndiceCadastro.addTab("Consultar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpIndiceCadastro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpIndiceCadastro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrarProduto(produto);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtProduto.setText(null);
        txtTamanho.setText(null);
        txtDescricao.setText(null);
        txtFornecedor.setText(null);
        txtPrecoCusto.setText(null);
        txtPrecoVenda.setText(null);
        txtICMS.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnLimparConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparConsultarActionPerformed
        txtProdutoConsultar.setText(null);
        txtTamanhoConsultar.setText(null);
        txtDescricaoConsultar.setText(null);
        txtFornecedorConsultar.setText(null);
        txtPrecoCustoConsultar.setText(null);
        txtPrecoVendaConsultar.setText(null);
        txtICMSConsultar.setText(null);
    }//GEN-LAST:event_btnLimparConsultarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        consultarProduto(produto);
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        deletarProduto(produto);
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        atualizarProduto(produto);
    }//GEN-LAST:event_btnAtualizarActionPerformed
    
    private void consultarProduto(Produto consultarProduto){
        this.conectar.conectaBanco();
        
        String query = "SELECT produto, tamanho, descricao, fornecedor, custo, venda, icms"
                + " FROM banco_loja.cadastroproduto WHERE produto LIKE '%" + txtProdutoConsultar.getText() + "%';" ;
        
        try {
            this.conectar.executarSQL(query);
            
            while (this.conectar.getResultSet().next()) {                
                consultarProduto.setProduto(this.conectar.getResultSet().getString(1));
                consultarProduto.setTamanho(this.conectar.getResultSet().getInt(2));
                consultarProduto.setDescricao(this.conectar.getResultSet().getString(3));
                consultarProduto.setFornecedor(this.conectar.getResultSet().getString(4));
                consultarProduto.setCusto(this.conectar.getResultSet().getFloat(5));
                consultarProduto.setVenda(this.conectar.getResultSet().getFloat(6));
                consultarProduto.setIcms(this.conectar.getResultSet().getFloat(7));
            }
                       
        } catch (Exception e) {
            System.out.println("Erro ao consultar produto " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
        } finally {
            txtProdutoConsultar.setText(consultarProduto.getProduto());
            txtTamanhoConsultar.setText(String.valueOf(consultarProduto.getTamanho()));
            txtDescricaoConsultar.setText(consultarProduto.getDescricao());
            txtFornecedorConsultar.setText(consultarProduto.getFornecedor());
            txtPrecoCustoConsultar.setText(String.valueOf(consultarProduto.getCusto()));
            txtPrecoVendaConsultar.setText(String.valueOf(consultarProduto.getVenda()));
            txtICMSConsultar.setText(String.valueOf(consultarProduto.getIcms()));
            this.conectar.fechaBanco();            
        }
    }
    
    private void cadastrarProduto(Produto novoProduto){
        this.conectar.conectaBanco();
        novoProduto.setProduto(txtProduto.getText());
        novoProduto.setDescricao(txtDescricao.getText());
        novoProduto.setFornecedor(txtFornecedor.getText());
        novoProduto.setTamanho(Integer.parseInt(txtTamanho.getText()));
        novoProduto.setCusto(Float.parseFloat(txtPrecoCusto.getText()));
        novoProduto.setVenda(Float.parseFloat(txtPrecoVenda.getText()));
        novoProduto.setIcms(Float.parseFloat(txtICMS.getText()));

        try {
            conectar.insertSQL("INSERT INTO cadastroproduto VALUES (null, '"
                    + novoProduto.getProduto() + "', " 
                    + novoProduto.getTamanho() + ", '"
                    + novoProduto.getDescricao() + "', '"
                    + novoProduto.getFornecedor() + "', "
                    + novoProduto.getCusto() + ", "
                    + novoProduto.getVenda() + ", "                    
                    + novoProduto.getIcms() + ");");
        } catch (Exception e) {
            System.out.println("Erro ao cadastrar produto " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto");
        } finally{
            this.conectar.fechaBanco();
            JOptionPane.showMessageDialog(null, "Cadastro de " + novoProduto.getProduto() + " efetuado com sucesso");
        }
    }
    
    private void deletarProduto(Produto deletarProduto){
        this.conectar.conectaBanco();
        
        String query = "DELETE FROM cadastroproduto WHERE produto LIKE '" + txtProdutoConsultar.getText() + "';";
        
        try {
            this.conectar.updateSQL(query);
            deletarProduto.setProduto(null);
            deletarProduto.setDescricao(null);
            deletarProduto.setFornecedor(null);
            deletarProduto.setCusto(0);
            deletarProduto.setVenda(0);
            deletarProduto.setIcms(0);
            deletarProduto.setTamanho(0);
            
            JOptionPane.showMessageDialog(null, "Produto deletado com sucesso");
        } catch (Exception e) {
            System.out.println("Erro ao deletar produto" + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao deletar cliente");
        } finally{
            this.conectar.fechaBanco();
        }
    }
    
    private void atualizarProduto(Produto atualizarProduto){
        
        atualizarProduto.setProduto(txtProdutoConsultar.getText());
        atualizarProduto.setDescricao(txtDescricaoConsultar.getText());
        atualizarProduto.setFornecedor(txtFornecedorConsultar.getText());
        atualizarProduto.setTamanho(Integer.parseInt(txtTamanhoConsultar.getText()));
        atualizarProduto.setCusto(Float.parseFloat(txtPrecoCustoConsultar.getText()));
        atualizarProduto.setVenda(Float.parseFloat(txtPrecoVendaConsultar.getText()));
        atualizarProduto.setIcms(Float.parseFloat(txtICMSConsultar.getText()));
        
        String query = "UPDATE cadastroproduto SET "
                + "produto = '" + atualizarProduto.getProduto() + "', "
                + "tamanho = " + atualizarProduto.getTamanho() + ", "
                + "descricao = '" + atualizarProduto.getDescricao() + "', "
                + "fornecedor = '" + atualizarProduto.getFornecedor() + "', "
                + "custo = " + atualizarProduto.getCusto() + ", "
                + "venda = " + atualizarProduto.getVenda() + ", "
                + "icms = " + atualizarProduto.getIcms()
                + " WHERE produto LIKE '" + atualizarProduto.getProduto() + "';";
        this.conectar.conectaBanco();
        try {
            if(atualizarProduto.getProduto().equals(""))
                JOptionPane.showMessageDialog(null, "Por favor, informe um nome a ser buscado");
            else{
                this.conectar.updateSQL(query);
                JOptionPane.showMessageDialog(null, "O produto " + atualizarProduto.getProduto() + " foi atualizado com sucesso");
            }
        } catch (Exception e){
            System.out.println("Erro ao atualizar produto " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao atualizar produto");
        } finally {
            this.conectar.fechaBanco();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparConsultar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblDescricaoConsultar;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblFornecedorConsultar;
    private javax.swing.JLabel lblICMS;
    private javax.swing.JLabel lblICMSConsultar;
    private javax.swing.JLabel lblPrecoCusto;
    private javax.swing.JLabel lblPrecoCustoConsultar;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblPrecoVendaConsultar;
    private javax.swing.JLabel lblProdutoConsultar;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTamanhoConsultar;
    private javax.swing.JTabbedPane tpIndiceCadastro;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricaoConsultar;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtFornecedorConsultar;
    private javax.swing.JTextField txtICMS;
    private javax.swing.JTextField txtICMSConsultar;
    private javax.swing.JTextField txtPrecoCusto;
    private javax.swing.JTextField txtPrecoCustoConsultar;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtPrecoVendaConsultar;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtProdutoConsultar;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JTextField txtTamanhoConsultar;
    // End of variables declaration//GEN-END:variables
}
